// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8CZJSNwuNaxLuFNiiv6ARpSmdOeClVLM',
    appId: '1:1021245758019:web:9f017d6a2f9196969852f6',
    messagingSenderId: '1021245758019',
    projectId: 'summary-text-2c844',
    authDomain: 'summary-text-2c844.firebaseapp.com',
    storageBucket: 'summary-text-2c844.appspot.com',
    measurementId: 'G-KKDNQ7BTWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqUGYejb7XqIs9TNO7SxX42Aev3zO_v20',
    appId: '1:1021245758019:android:4079b93e4f727b5d9852f6',
    messagingSenderId: '1021245758019',
    projectId: 'summary-text-2c844',
    storageBucket: 'summary-text-2c844.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByDaUKYfJ5bcUTJNSxUmZ-Cw4PxLVf9oE',
    appId: '1:1021245758019:ios:10c604f180d42a0b9852f6',
    messagingSenderId: '1021245758019',
    projectId: 'summary-text-2c844',
    storageBucket: 'summary-text-2c844.appspot.com',
    androidClientId: '1021245758019-t9vpiteqfts3gn8309d6b5n12t1mkvmg.apps.googleusercontent.com',
    iosClientId: '1021245758019-3apmanj8k5ei9heu91rlg6thfemevb4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.textSummaryEdit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByDaUKYfJ5bcUTJNSxUmZ-Cw4PxLVf9oE',
    appId: '1:1021245758019:ios:10c604f180d42a0b9852f6',
    messagingSenderId: '1021245758019',
    projectId: 'summary-text-2c844',
    storageBucket: 'summary-text-2c844.appspot.com',
    androidClientId: '1021245758019-t9vpiteqfts3gn8309d6b5n12t1mkvmg.apps.googleusercontent.com',
    iosClientId: '1021245758019-3apmanj8k5ei9heu91rlg6thfemevb4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.textSummaryEdit',
  );
}
